#backend/app/infra/monitoring/fail2ban/fastapi.conf




# fastapi.conf - Filtre pour détecter les attaques FastAPI
[Definition]
failregex = ^.*"POST /auth/login" .* 401.*client <HOST>.*$
            ^.*"POST /auth/signup" .* 401.*client <HOST>.*$
            ^.*429 Too Many Requests.*client <HOST>.*$

ignoreregex =